webapp/hortifruti/hortifruti/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from website import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'index_home.html'}),
                       url(r'^logout/$', views.logout_index, name='logout_home'),
                       url(r'^website/', include('website.urls')),
)

webapp/hortifruti/website/urls.py
from django.conf.urls import patterns, url

from website import views
from hortifruti import settings

urlpatterns = patterns('',
                       url(r'^$', views.index, name='website_index'),
                       url(r'^insercoes$', views.insercoes, name='insercoes'),
                       url(r'^cadastrar_pessoa/', views.cadastrar_pessoa, name='cadastrar_pessoa'),
                       url(r'^cadastrar_produto/', views.cadastrar_produto, name='cadastrar_produto'),
                       url(r'^cadastrar_pedido_admin/', views.cadastrar_pedido_admin, name='cadastrar_pedido_admin'),

                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT,'show_indexes': True}),#DEBUG
)

webapp/hortifruti/website/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User
from sorl.thumbnail import get_thumbnail

def date_time_field_to_str(date):
    string = str(date.day) + '/' + str(date.month) + '/' + str(date.year) + ' ' + str(date.hour) + ':' + str(date.minute)
    return string

class Mensagem(models.Model):
	nome = models.CharField(max_length=200, blank=False, default='')
	email = models.CharField(max_length=200, blank=False, default='')
	telefone = models.CharField(max_length=200, blank=True)
	mensagem = models.TextField(blank=False)

class Pessoa(models.Model):
    user = models.OneToOneField(User)
    url_externo = models.URLField(default='') 
    ultima_modificacao = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.user.first_name

    def as_json(self,thumbnail_size='267x300',thumbnail_crop='center'):
        d = dict(first_name=self.user.first_name,
                 last_name=self.user.last_name,
                 email=self.user.email,
                 ativo=self.user.is_active,
                 login=self.user.username,
                 id=self.id,
                 user=self.user.id,
                 url_externo = self.url_externo,
        )
        list_telefone = Telefone.objects.filter(pessoa=self)
        if len(list_telefone) > 0:
            d['ddd'] = list_telefone[0].ddd
            d['numero'] = list_telefone[0].numero
        if len(list_telefone) > 1:
            d['ddd2'] = list_telefone[1].ddd
            d['numero2'] = list_telefone[1].numero

        list_endereco = Endereco.objects.filter(pessoa=self)
        if len(list_endereco) > 0:
            d['cep'] = list_endereco[0].cep
            d['rua'] = list_endereco[0].rua
            d['numero_endereco'] = list_endereco[0].numero
            d['bairro'] = list_endereco[0].bairro
            d['cidade'] = list_endereco[0].cidade
            d['estado'] = list_endereco[0].estado
            d['complemento'] = list_endereco[0].complemento

        list_minha_imagem = ImagemPessoa.objects.filter(pessoa=self)
        if len(list_minha_imagem) > 0:
            d['url_imagem'] = get_thumbnail(list_minha_imagem[0].original,thumbnail_size,crop=thumbnail_crop).url
            d['tem_imagem'] = True        
        else:
            d['url_imagem'] = get_thumbnail(ImagemPadrao.objects.get(uso='user_image').imagem,thumbnail_size,crop=thumbnail_crop).url
            d['tem_imagem'] = False
        return d

#User.objects.create_superuser('gabriel', 'abc@123.com', 'abc123')
#from django.contrib.auth.models import User
class Telefone(models.Model):
    class Meta:
        ordering = ['ddd', 'numero']
        unique_together = 'ddd', 'numero'

    pessoa = models.ForeignKey('Pessoa')
    ddd = models.CharField(max_length=3)
    numero = models.CharField(max_length=9)

    def __unicode__(self):
        return ('(' + self.ddd + ')' + self.numero)

class Endereco(models.Model):
    class Meta:
        ordering = ['pessoa']

    pessoa = models.OneToOneField('Pessoa', primary_key=True)
    cep = models.CharField(max_length=8)
    rua = models.CharField(max_length=200)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50, default='Recife')
    estado = models.CharField(max_length=50, default='Pernambuco')
    complemento = models.CharField(max_length=200, blank=True)

class Produto(models.Model):
    nome = models.CharField(max_length=50)
    preco = models.DecimalField(max_digits=19, decimal_places=2)
    UNIDADE_CHOICES = (
        ('KG', 'Quilograma'),
        ('CX', 'Caixa'),
        ('BD', 'Balde'),
        ('ML', 'Molho'),
        ('UND', 'Unidade'),
    )
    unidade = models.CharField(max_length=3, choices=UNIDADE_CHOICES, default='KG')
    CATEGORY_CHOICES = (
        ('F', 'Frutas'),
        ('LE', 'Legumes'),
        ('V', 'Verduras'),
        ('C', 'Carnes'),
        ('LA', 'Laticínios'),
        ('T', 'Temperos'),
        ('UT', 'Utilidades'),
        ('O', 'Outros'),
    )
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)

    criado = models.DateTimeField(auto_now_add=True,default=timezone.now)
    ultima_modificacao = models.DateTimeField(auto_now=True,default=timezone.now)
    compra_minima = models.DecimalField(max_digits=19, decimal_places=2,default='0.00')
    granularidade = models.DecimalField(max_digits=19, decimal_places=2,default='0.00')
    disponivel = models.BooleanField(default=True)
    #As compras validas são nas quantidades x:
    #se granularidade == 0: x >= compra_minima
    #se não :  x = compra_minima + granularidade*d, onde d = 0,1,2..

    def __unicode__(self):
        return self.nome

    def as_json(self,thumbnail_size='267x300',thumbnail_crop='center'):
        d = dict(
            nome=unicode(self.nome),
            preco=str(self.preco),
            unidade=str(self.unidade),
            category=str(self.category),
            criado=date_time_field_to_str(self.criado),
            ultima_modificacao=date_time_field_to_str(self.ultima_modificacao),
            compra_minima=str(self.compra_minima),
            granularidade=str(self.granularidade),
            disponivel=self.disponivel,
            id=str(self.id)
        )

        list_minha_imagem = ImagemProduto.objects.filter(produto=self)
        if len(list_minha_imagem) > 0:
            d['url_imagem'] = get_thumbnail(list_minha_imagem[0].original,thumbnail_size,crop=thumbnail_crop).url
        else:
            d['url_imagem'] = get_thumbnail(ImagemPadrao.objects.get(uso='produto').imagem,thumbnail_size,crop=thumbnail_crop).url
        return d

class Pedido(models.Model):
    class Meta:
        ordering = ['data_pedido']

    pessoa = models.ForeignKey('Pessoa')

    produtos = models.ManyToManyField('Produto', through='Pedido_Produto')

    data_pedido = models.DateTimeField(auto_now_add=True)
    data_entrega = models.DateTimeField()
    valor_total = models.DecimalField(max_digits=19, decimal_places=2)
    valor_pago = models.DecimalField(default=0.00, max_digits=19, decimal_places=2)
    cancelado = models.BooleanField(default=False)
    entregue = models.BooleanField(default=False)
    pago = models.BooleanField(default=False)
    observacao = models.CharField(max_length=200, blank=True, default='')

    ultima_modificacao = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.pessoa.user.first_name + ' ' + str(self.id)

    def as_json(self,thumbnail_size='267x300',thumbnail_crop='center'):
        d = dict(pessoa_first_name=self.pessoa.user.first_name,
                    data_pedido=str(self.data_pedido),
                    data_entrega=str(self.data_entrega),
                    valor_total=str(self.valor_total),
                    valor_pago=str(self.valor_pago),
                    cancelado=self.cancelado,
                    entregue=self.entregue,
                    pago=self.pago,
                    obervacao=self.observacao,
                    id=self.id
        )
        list_minha_imagem = ImagemPessoa.objects.filter(pessoa=self.pessoa)
        if len(list_minha_imagem) > 0:
            d['url_imagem'] = get_thumbnail(list_minha_imagem[0].original,thumbnail_size,crop=thumbnail_crop).url
        else:
            d['url_imagem'] = get_thumbnail(ImagemPadrao.objects.get(uso='user_image').imagem,thumbnail_size,crop=thumbnail_crop).url
        return d

class Pedido_Produto(models.Model):
    class Meta:
        ordering = ['pedido', 'produto']

    pedido = models.ForeignKey('Pedido')
    produto = models.ForeignKey('Produto')
    preco_total = models.DecimalField(max_digits=19,
                                              decimal_places=2)  # automatico quantidade_produto*preco_unidade_produto - desconto*qtd
    preco_produto = models.DecimalField(max_digits=19,
                                                decimal_places=2)
    preco_produto_final = models.DecimalField(max_digits=19, decimal_places=2)
    quantidade_produto = models.DecimalField(max_digits=19, decimal_places=2)  # check maior que 0

    def __unicode__(self):
        return (self.pedido.pessoa.user.first_name + ' ' + str(self.pedido.id) + ' | ' + self.produto.nome + ' ' + str(
            self.produto.id) + ' | ' + str(self.id))

    def as_json(self):
        return dict(
            produto=self.produto.id,
            produto_nome=self.produto.nome,
            produto_und=self.produto.unidade,
            preco=str(self.preco_produto),
            precoF=str(self.preco_produto_final),
            qtd=str(self.quantidade_produto),
            total=str(self.preco_total),
            id=self.id
        )

class ImagemPessoa(models.Model):
    pessoa = models.OneToOneField('Pessoa', primary_key=True)
    original = models.ImageField(blank=False,upload_to='pessoa')
    criado = models.DateTimeField(auto_now_add=True)
    ultima_modificacao = models.DateTimeField(auto_now=True)

class ImagemProduto(models.Model):
    produto = models.OneToOneField('Produto', primary_key=True)
    original = models.ImageField(blank=False,upload_to='produto')
    criado = models.DateTimeField(auto_now_add=True)
    ultima_modificacao = models.DateTimeField(auto_now=True)

class ImagemPadrao(models.Model):
    uso = models.TextField(primary_key=True,max_length=20)
    imagem = models.ImageField(blank=False,upload_to='padrao')

webapp/hortifruti/website/forms.py
# -*- coding: utf-8 -*-
from django.utils.translation import gettext as _
from localflavor.br.forms import BRCPFField, BRCNPJField, BRPhoneNumberField, BRZipCodeField, BRStateChoiceField
from django.forms.formsets import formset_factory
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

from models import *


class Pedido_Produto_Form(forms.Form):
    desconto = forms.DecimalField(max_digits=19, decimal_places=2)
    quantidade = forms.DecimalField(max_digits=19, decimal_places=2)
    preco = forms.DecimalField(max_digits=19, decimal_places=2, widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    def __init__(self, *args, **kwargs):
        super(Pedido_Produto_Form, self).__init__(*args, **kwargs)
        produtos = [('', '-----')]
        for produto in Produto.objects.all():
            produtos = produtos + [(produto.id, produto.nome)]
        self.fields['produto'] = forms.ChoiceField(widget=forms.Select(), choices=produtos)


class Pedido_Admin_Form(forms.Form):
    usuario = forms.ChoiceField()

    data_entrega = forms.DateField(widget=AdminDateWidget)

    valor_total = forms.DecimalField(max_digits=19, decimal_places=2,
                                     widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    valor_pago = forms.DecimalField(max_digits=19, decimal_places=2)

    cancelado = forms.BooleanField(required=False)

    entregue = forms.BooleanField(required=False)

    pago = forms.BooleanField(required=False)

    observacao = forms.CharField(max_length=200, required=False)

    PedidoProdutoFormset = formset_factory(Pedido_Produto_Form)

    pedido_produto_formset = PedidoProdutoFormset(prefix='pedidoprodutos')


class Cadastro_Produto_Form(forms.Form):
    nome = forms.CharField(max_length=50)
    preco = forms.DecimalField(max_digits=19, decimal_places=2)
    disponivel = forms.BooleanField(required=False)
    UNIDADE = [('KG', 'Quilograma'), ('CX', 'Caixa'), ('BD', 'Balde'), ('ML', 'Molho'), ('UND', 'Unidade')]
    unidade = forms.ChoiceField(choices=UNIDADE, widget=forms.RadioSelect())


class Cadastro_Usuario_Form(forms.Form):
    error_messages = {
        'duplicate_username': _("Um usuário com esse nome já existe."),
        'password_mismatch': _("Os dois campos de senha não estão iguais."),
    }

    login = forms.RegexField(label=_("Login"), max_length=20,
                             regex=r'^[\w.@+-]+$',
                             help_text=_("<br /><br />"),
                             error_messages={'invalid': _("Este campo contém letras, números e @/./+/-/_ apenas."),
                                             'required': "Por favor preencha este campo."})

    password1 = forms.CharField(label=_("Senha"), error_messages={'required': "Por favor preencha este campo."},
                                widget=forms.PasswordInput)

    password2 = forms.CharField(label=_("Confirmação de Senha"), widget=forms.PasswordInput,
                                error_messages={'required': "Por favor preencha este campo."})

    nome = forms.CharField(label=_("Nome"), max_length=100,
                           error_messages={'required': "Por favor preencha este campo."})

    email = forms.EmailField(label=_("Email"), max_length=200, required=False)

    CHOICE = [('M', 'Masculino'), ('F', 'Feminino'), ('ND', 'Não definido')]
    sexo = forms.ChoiceField(choices=CHOICE, widget=forms.RadioSelect(),
                             error_messages={'required': "Por favor preencha este campo."})

    TIPO = [('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica'), ('admin', 'Administrador')]
    tipo = forms.ChoiceField(choices=TIPO, widget=forms.RadioSelect(),
                             error_messages={'required': "Por favor preencha este campo."})

    cpf = BRCPFField(label=_("CPF"), required=False)

    cnpj = BRCNPJField(label=_("CNPJ"), required=False)

    class Telefone_Form(forms.Form):
        telefone = BRPhoneNumberField(label=_("telefone"), required=False, error_messages={
            'invalid': _(('Números de telefone devem estar no seguinte formato: XX-XXXX-XXXX ou XX-XXXXX-XXXX.')), })

    TelefoneFormset = formset_factory(Telefone_Form)

    telefone_formset = TelefoneFormset(prefix='telefones')

    estado = BRStateChoiceField()

    cidade = forms.CharField(max_length=50)

    cep = BRZipCodeField(max_length=9)

    rua = forms.CharField(max_length=200)

    numero = forms.IntegerField()

    bairro = forms.CharField(max_length=50)

    complemento = forms.CharField(max_length=200, required=False)

    class Meta:
        model = Pessoa
        fields = ("login", "password1", "password2", "nome", "email", "sexo", "tipo")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

webapp/hortifruti/website/templates/cadastro/cliente.html
<html>
<head>
    <title>Cadastro de Cliente</title>

    <script type="text/html" id="telefone-template">
        <div id="telefone-__prefix__">
            {{ form.telefone_formset.empty_form.telefone }}
        </div>
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            cpf = $('#cpf_wrapper');
            cpf.hide();
            cnpj = $('#cnpj_wrapper');
            cnpj.hide();

            clear_fields = function () {
                rad = $('input[name=tipo]');
                valor = rad.filter(':checked').val();
                if (valor == "fisica") {
                    cpf.show();
                    $('#id_cpf').attr('required', true);
                    cnpj.hide();
                    $('#id_cnpj').attr('required', false);
                    $('#id_cnpj').val("");
                } else if (valor == "juridica") {
                    cnpj.show();
                    $('#id_cnpj').attr('required', true);
                    cpf.hide();
                    $('#id_cpf').attr('required', false);
                    $('#id_cpf').val("");
                } else {
                    cpf.hide();
                    $('#id_cpf').attr('required', false);
                    cnpj.hide();
                    $('#id_cnpj').attr('required', false);
                    $('#id_cpf').val("");
                    $('#id_cnpj').val("");
                }
            };

            clear_fields();

            $('#id_tipo').click(function () {
                clear_fields();
            });

            $('.add-telefone').click(function (ev) {
                ev.preventDefault();
                var count = $('#telefones_forms_container').children().length - 1; //Nao sei por que aqui fica -1
                var tmplMarkup = $('#telefone-template').html();
                var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
                $('div#telefones_forms_container').append(compiledTmpl);

                $('#id_telefones-TOTAL_FORMS').attr('value', count + 1); //E aqui +1, mas funciona assim
            });
        });
    </script>
</head>
<body>

<h1> Cadastro de Cliente</h1>

<form action="{% url 'cadastrar_pessoa' %}" method="post" id="cadastro">
{% csrf_token %}
{{ form.non_field_errors }}
<div class="fieldWrapper">
    {% if form.login.errors %}
    <ol>
        {% for error in form.login.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_login">Login:<br/></label>
    {{ form.login }}
</div>
<div class="fieldWrapper">
    {% if form.nome.errors %}
    <ol>
        {% for error in form.nome.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_nome">Nome:<br/></label>
    {{ form.nome }}
</div>
<div class="fieldWrapper">
    {% if form.password1.errors %}
    <ol>
        {% for error in form.password1.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_password1">Senha:<br/></label>
    {{ form.password1 }}
</div>
<div class="fieldWrapper">
    {% if form.password2.errors %}
    <ol>
        {% for error in form.password2.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_password2">Repita a senha:<br/></label>
    {{ form.password2 }}
</div>

{{ form.telefone_formset.management_form }}
<div id="telefones_forms_container">
    Telefone(s): <br/>
    {% for telefoneform in form.telefone_formset %}

    {% if telefoneform.telefone.errors %}
    <ol>
        {% for error in telefoneform.telefone.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}

    <div id="telefone-{{ forloop.counter0 }}">
        {{ telefoneform.telefone }}
        {% if forloop.counter0 == 0 %}
        <a href="#" id="add_telefone" class="btn btn-info add-telefone"><img src="/static/admin/img/icon_addlink.gif"
                                                                             width="10" height="10"
                                                                             alt="Adicionar Outro"/></a>
        {% endif %}
    </div>
    {% endfor %}
</div>
<div class="fieldWrapper">
    {% if form.email.errors %}
    <ol>
        {% for error in form.email.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_email"><i>E-mail</i>:<br/></label>
    {{ form.email }}
</div>
<br/>Endereço: <br/>

<div class="fieldWrapper">
    {% if form.estado.errors %}
    <ol>
        {% for error in form.estado.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_estado">Estado:<br/></label>
    &emsp;&emsp;{{ form.estado }}
</div>
<div class="fieldWrapper">
    {% if form.cidade.errors %}
    <ol>
        {% for error in form.cidade.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_cidade">Cidade:<br/></label>
    &emsp;&emsp;{{ form.cidade }}
</div>
<div class="fieldWrapper">
    {% if form.cep.errors %}
    <ol>
        {% for error in form.cep.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_cep">CEP:<br/></label>
    &emsp;&emsp;{{ form.cep }}
</div>
<div class="fieldWrapper">
    {% if form.rua.errors %}
    <ol>
        {% for error in form.rua.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_rua">Rua:<br/></label>
    &emsp;&emsp;{{ form.rua }}
</div>
<div class="fieldWrapper">
    {% if form.numero.errors %}
    <ol>
        {% for error in form.numero.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_numero">Número:<br/></label>
    &emsp;&emsp;{{ form.numero }}
</div>
<div class="fieldWrapper">
    {% if form.bairro.errors %}
    <ol>
        {% for error in form.bairro.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_bairro">Bairro:<br/></label>
    &emsp;&emsp;{{ form.bairro }}
</div>
<div class="fieldWrapper">
    {% if form.complemento.errors %}
    <ol>
        {% for error in form.complemento.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    &emsp;&emsp;<label for="id_complemento"><i>Complemento</i>:<br/></label>
    &emsp;&emsp;{{ form.complemento }}
</div>
<br/>

<div class="fieldWrapper">
    {% if form.sexo.errors %}
    <ol>
        {% for error in form.sexo.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_sexo">Sexo:<br/></label>
    {{ form.sexo }}
</div>
<div class="fieldWrapper">
    {% if form.tipo.errors %}
    <ol>
        {% for error in form.tipo.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_tipo">Tipo de conta:<br/></label>
    {{ form.tipo }}
</div>
<div class="fieldWrapper" id="cpf_wrapper">
    {% if form.cpf.errors %}
    <ol>
        {% for error in form.cpf.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_cpf">CPF:<br/></label>
    {{ form.cpf }}
</div>
<div class="fieldWrapper" id="cnpj_wrapper">
    {% if form.cnpj.errors %}
    <ol>
        {% for error in form.cnpj.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
    {% endif %}
    <label for="id_cnpj">CNPJ:<br/></label>
    {{ form.cnpj }}
</div>

<br/>
<input type="submit" value="Cadastrar" id="id_cadastrar"/>
</form>

</html>